"""SPIN - Self-Play Fine-Tuning (Reference Sec 47.200).

Chen, Deng, Yuan, Ji & Gu 2024 'Self-Play Fine-Tuning Converts
Weak Language Models to Strong Language Models', ICML. Alternates:

    Round t: opponent = model_{t-1}. Player = model_t.
    Objective: model_t should distinguish HUMAN samples from
                 samples generated by model_{t-1}.

Loss = -log sigmoid(logp_pi_t(y_human) - logp_pi_t(y_from_opp))
No preference labels needed; the model improves by fooling its
own prior version. Similar to GAN training but with an
autoregressive LM.
"""
from __future__ import annotations    # stdlib

import numpy as np    # numerical arrays


def sigmoid(x):
    return 1 / (1 + np.exp(-np.clip(x, -50, 50)))


def spin_loss(logp_human, logp_opp, beta=0.5):
    """SPIN discrimination loss: prefer human over opponent samples."""
    return -np.log(sigmoid(beta * (logp_human - logp_opp)) + 1e-12)


def sample_from_theta(theta, rng):
    """Sample one categorical index from softmax(theta)."""
    z = theta - theta.max(); p = np.exp(z); p = p / p.sum()
    return int(rng.choice(len(p), p=p))


if __name__ == "__main__":
    print("=== SPIN - Self-Play Fine-Tuning (Chen et al 2024) ===\n")
    rng = np.random.default_rng(0)

    # Ground-truth human distribution: peaks on responses [1, 3]
    Y = 6
    human_probs = np.array([0.05, 0.40, 0.05, 0.35, 0.10, 0.05])
    human_samples = rng.choice(Y, size=200, p=human_probs)

    # Initial (weak) policy: uniform-ish
    theta = np.zeros(Y)
    opp = theta.copy()

    def get_probs(t):
        z = t - t.max(); p = np.exp(z); return p / p.sum()

    for round_ in range(5):
        # Sample opponent responses
        opp_samples = [sample_from_theta(opp, rng) for _ in range(200)]

        # SPIN inner training loop: nudge theta to prefer humans over opp
        for step in range(500):
            grad = np.zeros(Y)
            # For each pair (human_i, opp_j), gradient step
            for hi in range(min(50, len(human_samples))):
                yh = human_samples[rng.integers(len(human_samples))]
                yo = opp_samples[rng.integers(len(opp_samples))]
                p = get_probs(theta)
                logp_h = np.log(p[yh] + 1e-12)
                logp_o = np.log(p[yo] + 1e-12)
                s = sigmoid(0.5 * (logp_h - logp_o))
                # dL/dtheta[k] = -(1-s)*0.5*(1[k=yh]/p[yh]*dp[yh]/dtheta[k] - ...)
                # Simplified: push theta[yh] up, theta[yo] down
                grad[yh] -= (1 - s)
                grad[yo] += (1 - s)
            theta -= 0.01 * grad / 50

        # KL to human
        p = get_probs(theta)
        kl = float(np.sum(p * np.log((p + 1e-12) / (human_probs + 1e-12))))
        print(f"  Round {round_ + 1}: KL(pi || human) = {kl:.3f}   pi = {np.round(p, 3)}")
        opp = theta.copy()

    print(f"\n  Target human: {np.round(human_probs, 3)}")
    print("  SPIN converges pi -> human distribution using only human samples,")
    print("  no preference labels. Each round the opponent (last-round model)")
    print("  provides new 'negatives' the current model must distinguish from.")

    print("\n--- library cross-check (SPIN-Anonymous/spin, trl SFTTrainer + custom loop) ---")
