"""Wavelet analysis (Reference §13.19).

Time-frequency decomposition that (unlike Fourier) resolves LOCAL structure
in a non-stationary signal.  A wavelet basis is generated by translating
and dilating a mother wavelet psi(t).

Discrete Wavelet Transform (DWT)
    Repeated filtering by a pair (h, g) of quadrature-mirror filters (h =
    scaling / low-pass, g = wavelet / high-pass) followed by downsampling
    by 2.  Result: a set of approximation and detail coefficients at
    different resolution levels.

Haar wavelet
    Simplest and fully explicit:
        h = [1/sqrt(2), 1/sqrt(2)]
        g = [1/sqrt(2), -1/sqrt(2)]
    Detail_j[k] = (x[2k] - x[2k+1]) / sqrt(2)   for level 1
    Approximation_j[k] = (x[2k] + x[2k+1]) / sqrt(2)

Daubechies-4 wavelet (db4)
    Compactly-supported orthonormal wavelet with 2 vanishing moments;
    the standard workhorse for smooth signals with occasional jumps.

Denoising by soft thresholding (Donoho-Johnstone 1994)
    1. DWT of noisy signal.
    2. Threshold detail coefficients: d' = sign(d) max(|d| - lambda, 0)
       with universal threshold lambda = sigma sqrt(2 log N).
    3. Inverse DWT.
    Optimal minimax denoising under a wide class of signal classes.
"""
from __future__ import annotations    # stdlib: postpone type-hint evaluation (lets us write int | None)

import math    # stdlib: scalar math (sqrt, log, exp, comb, lgamma, pi, ...)

import numpy as np    # numerical arrays + linear algebra (np.mean, np.linalg.lstsq, ...)


# --- Filter banks --------------------------------------------------------
H_HAAR = np.array([1, 1]) / math.sqrt(2)
G_HAAR = np.array([1, -1]) / math.sqrt(2)

# Daubechies-4 low-pass filter (four taps)
_c = math.sqrt(3)
H_DB4 = np.array([1 + _c, 3 + _c, 3 - _c, 1 - _c]) / (4 * math.sqrt(2))
G_DB4 = np.array([H_DB4[3], -H_DB4[2], H_DB4[1], -H_DB4[0]])


def _pad_pow2(x):
    n = len(x); m = 1 << int(math.ceil(math.log2(n)))
    return np.pad(x, (0, m - n)), n


def _dwt_step(x, h, g):
    L = len(h)
    # Circular convolution + downsample by 2
    N = len(x)
    x_ext = np.concatenate([x, x[:L - 1]])
    lo = np.array([np.dot(h, x_ext[2 * k:2 * k + L]) for k in range(N // 2)])
    hi = np.array([np.dot(g, x_ext[2 * k:2 * k + L]) for k in range(N // 2)])
    return lo, hi


def _idwt_step(lo, hi, h, g):
    L = len(h); N2 = len(lo); N = 2 * N2
    x = np.zeros(N)
    # Upsample and reconstruct via the (reversed) synthesis filters
    for k in range(N2):
        for l in range(L):
            idx = (2 * k + l) % N
            x[idx] += lo[k] * h[l] + hi[k] * g[l]
    return x


def dwt(x, wavelet: str = "haar", n_levels: int = 3) -> dict:
    """Multi-level DWT; returns approx and per-level details."""
    if wavelet == "haar": h, g = H_HAAR, G_HAAR
    elif wavelet == "db4": h, g = H_DB4, G_DB4
    else: raise ValueError("wavelet must be 'haar' or 'db4'")
    x_padded, n_orig = _pad_pow2(np.asarray(x, dtype=float))
    approx = x_padded.copy()
    details = []
    for _ in range(n_levels):
        approx, d = _dwt_step(approx, h, g)
        details.append(d)
    return {"approximation": approx, "details": details,
            "n_levels": int(n_levels), "n_original": int(n_orig),
            "wavelet": wavelet,
            "method": f"Discrete wavelet transform ({wavelet}, {n_levels} levels)"}


def idwt(approximation, details, wavelet: str = "haar"):
    """Inverse DWT from approximation + list of detail coefficients."""
    if wavelet == "haar": h, g = H_HAAR, G_HAAR
    elif wavelet == "db4": h, g = H_DB4, G_DB4
    else: raise ValueError("wavelet must be 'haar' or 'db4'")
    x = approximation
    for d in reversed(details):
        x = _idwt_step(x, d, h, g)
    return x


def wavelet_denoise(x, wavelet: str = "haar", n_levels: int = 3, sigma=None) -> dict:
    """Universal soft-threshold wavelet denoising (Donoho-Johnstone)."""
    x = np.asarray(x, dtype=float); N = len(x)
    w = dwt(x, wavelet=wavelet, n_levels=n_levels)
    # Estimate noise sigma from the level-1 detail (MAD / 0.6745)
    if sigma is None:
        sigma = float(np.median(np.abs(w["details"][0])) / 0.6745)
    lam = sigma * math.sqrt(2 * math.log(N))
    denoised_details = [np.sign(d) * np.maximum(np.abs(d) - lam, 0) for d in w["details"]]
    x_dn = idwt(w["approximation"], denoised_details, wavelet=wavelet)[:N]
    return {"x_denoised": x_dn,
            "sigma_estimate": sigma, "threshold": float(lam),
            "wavelet": wavelet, "n_levels": int(n_levels),
            "method": "Wavelet soft-threshold denoising (Donoho-Johnstone)"}


if __name__ == "__main__":
    rng = np.random.default_rng(0)
    N = 512
    t = np.linspace(0, 4 * math.pi, N)
    # Signal: sinusoid + step + noise
    x_clean = np.sin(t) + (t > 2 * math.pi).astype(float)
    x = x_clean + rng.normal(0, 0.3, N)

    print("=== Haar DWT (3 levels) ===")
    w = dwt(x, wavelet="haar", n_levels=3)
    print(f"  approximation shape: {w['approximation'].shape}")
    for j, d in enumerate(w["details"]):
        print(f"  level {j+1} detail shape: {d.shape}, energy = {(d ** 2).sum():.2f}")

    print("\n=== Perfect-reconstruction check (Haar) ===")
    x_rec = idwt(w["approximation"], w["details"], wavelet="haar")[:N]
    print(f"  max |x - x_rec| = {np.max(np.abs(x - x_rec)):.2e}")

    print("\n=== Wavelet soft-threshold denoising ===")
    r = wavelet_denoise(x, wavelet="haar", n_levels=4)
    mse_noisy = np.mean((x - x_clean) ** 2)
    mse_dn = np.mean((r["x_denoised"] - x_clean) ** 2)
    print(f"  sigma est: {r['sigma_estimate']:.3f}")
    print(f"  threshold: {r['threshold']:.3f}")
    print(f"  MSE noisy vs clean:    {mse_noisy:.4f}")
    print(f"  MSE denoised vs clean: {mse_dn:.4f}  ({100*(1-mse_dn/mse_noisy):.1f}% reduction)")

    print("\n--- library cross-check (pywt) ---")
    try:
        import pywt
        c_pywt = pywt.wavedec(x, "haar", level=3)
        print(f"  pywt wavedec: {len(c_pywt)} coefficient arrays ({[len(a) for a in c_pywt]})")
    except Exception as ex:
        print(f"  (pywt not available: {ex})")
